language: php

os: linux

dist: xenial

git:
  depth: 3

php:
  - '7.4.1'

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - composer install

script:
  - ./bin/phpunit -c ./phpunit.xml
