language: php

os: linux

dist: xenial

git:
  depth: 3

php:
  - '7.4.1'

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - composer install

script:
  - ./bin/phpunit -c ./phpunit.xml --coverage-clover=coverage.xml

env:
  - CODECOV_TOKEN="34400cde-9b49-4fed-8d91-6da51bda28f2"

after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)

