parameters:
  exchangerates_host: '%env(EXCHANGERATES_HOST)%'
  binlist_host: '%env(BINLIST_HOST)%'
  europe_commission_rate: '%env(EUROPE_COMMISSION_RATE)%'
  non_europe_commission_rate: '%env(NON_EUROPE_COMMISSION_RATE)%'
  version: 0.1

services:
  _defaults:
    autowire: true

  CommissionCalc\:
    resource: '../src/'
    exclude:
      - '../src/Models/'
      - '../src/Command/'

  CommissionCalc\EurCommissionCalc:
    arguments:
      $europeCommissionRate: '%europe_commission_rate%'
      $nonEuropeCommissionRate: '%non_europe_commission_rate%'

  CommissionCalc\ExchangeRatesRestClient:
    arguments:
      - !service
          class: GuzzleHttp\Client
      - '%exchangerates_host%'

  CommissionCalc\BinlistClient:
    arguments:
      - !service
          class: GuzzleHttp\Client
      - '%binlist_host%'

  Symfony\Component\Serializer\SerializerInterface:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      $normalizers:
        - !service
            class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
            arguments:
              - ~
              - ~
              - ~
              - !service
                  class: Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor
        - !service
            class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
      $encoders:
        - !service
            class: Symfony\Component\Serializer\Encoder\JsonEncoder

  # `````````````````````#
  # Console Application  #
  #......................#
  console_app:
    class: Symfony\Component\Console\Application
    public: true
    calls:
      - method: addCommands
        arguments:
          -
            - '@CommissionCalc\Command\PrintCommissionCommand'
      - method: setVersion
        arguments:
          - '%version%'
      - method: setName
        arguments:
          - 'COMMISSION CALC'

  CommissionCalc\Command\PrintCommissionCommand: ~
